const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
export function normaliseView(spawn,mapId,mode,partial={}){const v={mode,mapId,x:spawn.x??spawn[0],y:spawn.y??spawn[1],z:spawn.z??spawn[2],yaw:0,pitch:45,distance:120,zoom:1,...partial,mode,mapId};for(const key of ['x','y','z','yaw','pitch','distance','zoom'])if(!Number.isFinite(v[key]))throw new Error(`Invalid ${key}`);v.pitch=clamp(v.pitch,10,89);v.distance=clamp(v.distance,8,1024);v.zoom=clamp(v.zoom,1/16,16);return v;}
export function cameraPosition({x,y,z,yaw,pitch,distance}){const a=yaw*Math.PI/180,b=pitch*Math.PI/180;return{x:x-Math.sin(a)*distance*Math.cos(b),y:y+distance*Math.sin(b),z:z+Math.cos(a)*distance*Math.cos(b)};}
function multiply(a,b){const out=new Float64Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)out[c*4+r]+=a[k*4+r]*b[c*4+k];return out;}
export function viewProjection(v,aspect){const e=cameraPosition(v),f=[v.x-e.x,v.y-e.y,v.z-e.z],fl=Math.hypot(...f);for(let i=0;i<3;i++)f[i]/=fl;let r=[-f[2],0,f[0]],rl=Math.hypot(...r);if(rl<1e-12){r=[1,0,0];rl=1;}for(let i=0;i<3;i++)r[i]/=rl;const u=[r[1]*f[2]-r[2]*f[1],r[2]*f[0]-r[0]*f[2],r[0]*f[1]-r[1]*f[0]],m=new Float64Array([r[0],u[0],-f[0],0,r[1],u[1],-f[1],0,r[2],u[2],-f[2],0,-(r[0]*e.x+r[1]*e.y+r[2]*e.z),-(u[0]*e.x+u[1]*e.y+u[2]*e.z),f[0]*e.x+f[1]*e.y+f[2]*e.z,1]),s=1/Math.tan(75*Math.PI/360),n=.12,far=2000;return multiply(new Float64Array([s/aspect,0,0,0,0,s,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]),m);}
export function projectPoint(m,[x,y,z]){const w=m[3]*x+m[7]*y+m[11]*z+m[15];return[(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w];}
export function dragView(v,dx,dy,gesture,width,height){if(v.mode==='2d'||gesture==='pan'){if(v.mode==='2d')return{...v,x:v.x-dx/v.zoom,z:v.z-dy/v.zoom};const s=v.distance/Math.min(width,height),a=v.yaw*Math.PI/180;return{...v,x:v.x+(-dx*Math.cos(a)+dy*Math.sin(a))*s,z:v.z+(dx*Math.sin(a)+dy*Math.cos(a))*s};}return{...v,yaw:v.yaw+dx*.3,pitch:clamp(v.pitch+dy*.3,10,89)};}
export function pinchView(v,scale){return v.mode==='2d'?{...v,zoom:clamp(v.zoom*scale,1/16,16)}:{...v,distance:clamp(v.distance/scale,8,1024)};}
export function wheelScale(v,deltaY){return pinchView(v,Math.exp(-clamp(deltaY,-10000,10000)*.0015));}
export function keyView(v,code){if(v.mode==='3d'&&(code==='KeyQ'||code==='KeyE'))return{...v,yaw:v.yaw+(code==='KeyE'?10:-10)};const forward=code==='ArrowUp'||code==='KeyW'?1:code==='ArrowDown'||code==='KeyS'?-1:0,right=code==='ArrowRight'||code==='KeyD'?1:code==='ArrowLeft'||code==='KeyA'?-1:0;if(!forward&&!right)return v;const step=v.mode==='2d'?32/v.zoom:Math.max(4,v.distance*.1);if(v.mode==='2d')return{...v,x:v.x+right*step,z:v.z-forward*step};const angle=v.yaw*Math.PI/180;return{...v,x:v.x+(-Math.sin(angle)*forward+Math.cos(angle)*right)*step,z:v.z+(-Math.cos(angle)*forward-Math.sin(angle)*right)*step};}
