import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { inflateRawSync, inflateSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseHeader, decode2d, decode3d } from '../../src/engine/format.mjs';
import { coalesceRanges, loadRegion, loadIndex } from '../../src/engine/loader.mjs';
import { selectChunks, reconcileChunks, visibleRegions } from '../../src/engine/stream.mjs';
import { normaliseView, cameraPosition, viewProjection, projectPoint, orbitView, zoomView } from '../../src/engine/view.mjs';
import { meanLayers, rasteriseRegion } from '../../src/engine/map2d.mjs';
import { meshChunk } from '../../src/engine/mesh-js.mjs';
import { loadMesher } from '../../src/engine/wasm.mjs';
import { resolveMaterials } from '../../src/engine/materials.mjs';

const root = new URL('../fixtures-out/overworld/', import.meta.url);
const atlas = new URL('../../../feasibility_research/output/textures/26.3/atlas.png', import.meta.url);
const blocks = new URL('../../../feasibility_research/output/textures/26.3/blocks.json', import.meta.url);
function asV4(old) {
  const data=Buffer.alloc(old.length+2);
  old.copy(data,0,0,16);data[4]=5;data.writeInt16BE(32767,16);old.copy(data,18,16);
  let at=16;
  const varint=()=>{let value=0,shift=0,byte;do{byte=old[at++];value+=(byte&127)*2**shift;shift+=7;}while(byte&128);return value;};
  const table=()=>{const count=varint();for(let i=0;i<count;i++){const length=varint();at+=length;}};
  table();if(old[5]===1)table();
  for(let i=0;i<1024;i++){const offset=old.readUInt32BE(at+i*8);if(offset)data.writeUInt32BE(offset+2,at+2+i*8);}
  return data;
}
const region = async (suffix) => asV4(await readFile(new URL(`r.0.0.${suffix}`, root)));
function slowVarint(data, cursor) { let value=0, multiplier=1, byte; do { byte=data[cursor.at++]; value+=(byte&127)*multiplier; multiplier*=128; } while(byte&128); return value; }
function slowHeader(data, kind) { const cursor={at:18}, strings=()=>Array.from({length:slowVarint(data,cursor)},()=>{const n=slowVarint(data,cursor), value=new TextDecoder().decode(data.subarray(cursor.at,cursor.at+n)); cursor.at+=n; return value;}); const palette=strings(), biomes=kind===1?strings():[]; const entries=[]; for(let i=0;i<1024;i++){entries.push({index:i,start:data.readUInt32BE(cursor.at),length:data.readUInt32BE(cursor.at+4)});cursor.at+=8;} return {palette,biomes,entries}; }
function slow2d(raw){const cursor={at:0},columns=[];for(let i=0;i<256;i++){const y=raw.readInt16BE(cursor.at);cursor.at+=2;const block=slowVarint(raw,cursor),biome=slowVarint(raw,cursor),water=raw[cursor.at++];columns.push({y,block,biome,water});}assert.equal(cursor.at,raw.length);return columns;}
function slow3d(raw){const cursor={at:0}, positions=[],paletteIndices=[],masks=[];for(let sy=0;sy<24;sy++){const count=slowVarint(raw,cursor),part=[];let p=0;for(let i=0;i<count;i++){p+=slowVarint(raw,cursor);part.push(sy*4096+p);}for(let i=0;i<count;i++)paletteIndices.push(slowVarint(raw,cursor));for(let i=0;i<count;i++)masks.push(raw[cursor.at++]);positions.push(...part);}assert.equal(cursor.at,raw.length);return {positions,paletteIndices,masks};}

test('v5 header and real 2D/3D chunks match independent decoder',async()=>{for(const [kind,suffix,decode,reference] of [[1,'b2d',decode2d,slow2d],[2,'b3d',decode3d,slow3d]]){const data=await region(suffix),slow=slowHeader(data,kind),header=parseHeader(data,kind);assert.equal(header.version,5);assert.equal(header.maxY,32767);assert.deepEqual(header.palette,slow.palette);assert.deepEqual(header.biomes,slow.biomes);for(const entry of slow.entries.filter(e=>e.length).slice(0,4)){const raw=inflateRawSync(data.subarray(entry.start,entry.start+entry.length));const actual=decode(raw,header),expected=reference(raw);if(kind===1)assert.deepEqual(actual,expected);else{assert.ok(actual.positions instanceof Uint32Array);assert.ok(actual.paletteIndices instanceof Uint32Array);assert.ok(actual.masks instanceof Uint8Array);for(const field of ['positions','paletteIndices','masks'])assert.deepEqual(Array.from(actual[field]),expected[field]);}}}});
test('v3 format version is rejected with format code',async()=>{const data=Buffer.from(await region('b3d'));data[4]=3;assert.throws(()=>parseHeader(data,2),e=>e.code==='format');});
test('v5 maxY is read as a signed big-endian value',async()=>{const data=Buffer.from(await region('b3d'));data.writeInt16BE(-30,16);assert.equal(parseHeader(data,2).maxY,-30);data.writeInt16BE(100,16);assert.equal(parseHeader(data,2).maxY,100);});
test('range coalescing joins gaps of at most 4096',()=>{const entries=[{start:4200,length:2},{start:100,length:4},{start:8300,length:3},{start:13000,length:1}];assert.deepEqual(coalesceRanges(entries).map(r=>[r.start,r.end,r.entries.length]),[[100,4201,2],[8300,8302,1],[13000,13000,1]]);});
test('If-Range replacement discards old header and retries once',async()=>{const original=await region('b3d'),replacement=Buffer.from(original),calls=[];replacement[14]^=1;let changed=false;const fetcher=async(_url,options)=>{const range=options.headers.Range,etag=changed?'"new"':'"old"';calls.push([range,options.headers['If-Range']]);if(options.headers['If-Range'])changed=true;const body=changed?replacement:original;if(changed&&options.headers['If-Range']==='"old"')return new Response(body,{status:200,headers:{ETag:'"new"'}});const [start,end]=range.slice(6).split('-').map(Number);const bytes=body.subarray(start,Math.min(end+1,body.length));return new Response(bytes,{status:206,headers:{ETag:etag,'Content-Range':`bytes ${start}-${start+bytes.length-1}/${body.length}`}});};const loaded=await loadRegion('test',2,[0],{fetcher});assert.equal(loaded.header.flags,replacement[14]);assert.ok(calls.some(c=>c[1]==='"old"'));assert.ok(calls.some(c=>c[1]==='"new"'));});
test('second If-Range replacement fails without a retry loop',async()=>{const original=await region('b3d');let headers=0;const fetcher=async(_url,options)=>{const range=options.headers.Range;if(range==='bytes=0-65535')headers++;if(options.headers['If-Range'])return new Response(original,{status:200,headers:{ETag:`"${headers+1}"`}});const [start,end]=range.slice(6).split('-').map(Number),bytes=original.subarray(start,Math.min(end+1,original.length));return new Response(bytes,{status:206,headers:{ETag:`"${headers}"`,'Content-Range':`bytes ${start}-${start+bytes.length-1}/${original.length}`}});};await assert.rejects(loadRegion('test',2,[0],{fetcher}),/replaced repeatedly/);assert.equal(headers,2);});
test('selection, eviction and stale generations',()=>{const first=selectChunks(0,0,32),second=selectChunks(1000,0,32);const state=reconcileChunks(new Map(first.map(c=>[`${c.cx},${c.cz}`,{generation:1}])),second,1000,0,32,2);assert.ok(state.evict.length>0);assert.equal(state.accept({generation:1,cx:first[0].cx,cz:first[0].cz}),false);assert.equal(state.accept({generation:2,cx:second[0].cx,cz:second[0].cz}),true);assert.ok(visibleRegions([[0,0],[1,0]],0,0,800,600,1).some(r=>r[0]===0&&r[1]===0));});
test('view and gestures clamp, orbit and pinch',()=>{const v=normaliseView({x:0,y:64,z:0},'world','3d',{pitch:200,distance:2});assert.equal(v.pitch,89);assert.equal(v.distance,8);const moved=orbitView(v,100,20);assert.notEqual(moved.yaw,v.yaw);const zoomed=zoomView(v,800,600,null,2);assert.equal(zoomed.distance,8);const centre=projectPoint(viewProjection(v,1),[v.x,v.y,v.z]);assert.ok(Math.abs(centre[0])<1e-8&&Math.abs(centre[1])<1e-8);assert.ok(Number.isFinite(cameraPosition(v).x));});
test('loadIndex classifies HTTP, format and network failures',async()=>{await assert.rejects(loadIndex('./',{fetcher:async()=>new Response('',{status:404})}),e=>e.code==='http'&&e.status===404);await assert.rejects(loadIndex('./',{fetcher:async()=>new Response('{"format":2}') }),e=>e.code==='format');await assert.rejects(loadIndex('./',{fetcher:async()=>{throw new TypeError('offline')}}),e=>e.code==='network');});
test('loadIndex returns the parsed index and remembers its ETag for polling',async()=>{const expected={format:1,generated:1,textures:null,maps:[]};const actual=await loadIndex('./',{fetcher:async()=>new Response(JSON.stringify(expected),{headers:{ETag:'"one"'}})});assert.deepEqual(actual,expected);assert.equal(actual.etag,'"one"');const unchanged=await loadIndex('./',{etag:actual.etag,fetcher:async(_url,options)=>{assert.equal(options.headers['If-None-Match'],'"one"');return new Response(null,{status:304});}});assert.equal(unchanged.notModified,true);});
function decodePng(data){let at=8,width,height,packed=[];while(at<data.length){const n=data.readUInt32BE(at),type=data.toString('ascii',at+4,at+8),body=data.subarray(at+8,at+8+n);if(type==='IHDR'){width=body.readUInt32BE(0);height=body.readUInt32BE(4);}if(type==='IDAT')packed.push(body);at+=n+12;}const raw=inflateSync(Buffer.concat(packed)),out=Buffer.alloc(width*height*4),stride=width*4;for(let y=0;y<height;y++){const filter=raw[y*(stride+1)],src=y*(stride+1)+1;for(let x=0;x<stride;x++){const a=x>=4?out[y*stride+x-4]:0,b=y?out[(y-1)*stride+x]:0,c=y&&x>=4?out[(y-1)*stride+x-4]:0;let p=raw[src+x];if(filter===1)p+=a;else if(filter===2)p+=b;else if(filter===3)p+=Math.floor((a+b)/2);else if(filter===4){const q=a+b-c,da=Math.abs(q-a),db=Math.abs(q-b),dc=Math.abs(q-c);p+=da<=db&&da<=dc?a:db<=dc?b:c;}out[y*stride+x]=p&255;}}return {width,height,pixels:out};}
test('atlas layer means and real region raster agree with brute force',async()=>{const image=decodePng(await readFile(atlas)),table=JSON.parse(await readFile(blocks,'utf8'));const means=meanLayers(image.pixels,table.layers);for(let layer of [0,1,100,table.layers-1]){let sums=[0,0,0],n=0;for(let i=layer*256;i<(layer+1)*256;i++)if(image.pixels[i*4+3]>=128){for(let c=0;c<3;c++)sums[c]+=image.pixels[i*4+c];n++;}assert.deepEqual(Array.from(means.slice(layer*3,layer*3+3)),sums.map(s=>n?Math.round(s/n):0));}const data=await region('b2d'),header=parseHeader(data,1),entry=header.index.find(e=>e.length);const raw=inflateRawSync(data.subarray(entry.start,entry.start+entry.length));const columns=decode2d(raw,header);const actual=rasteriseRegion([{index:entry.index,columns}],header,table,means);assert.equal(actual.length,512*512*4);for(let i=0;i<256;i++){const c=columns[i],x=(entry.index%32)*16+i%16,z=Math.floor(entry.index/32)*16+Math.floor(i/16),at=(x+z*512)*4;if(c.y===-32768)assert.equal(actual[at+3],0);else assert.equal(actual[at+3],255);}});
test('real chunk JS and WASM greedy outputs are byte identical',async()=>{const data=await region('b3d'),header=parseHeader(data,2),table=JSON.parse(await readFile(blocks,'utf8')),materials=resolveMaterials(header.palette,table),wasm=(await loadMesher()).meshChunk;for(const entry of header.index.filter(e=>e.length).slice(0,3)){const chunk=decode3d(inflateRawSync(data.subarray(entry.start,entry.start+entry.length)),header),input={...chunk,materials};const js=meshChunk(input,'greedy'),rs=wasm(input,'greedy');assert.deepEqual(rs.vertices,js.vertices);assert.deepEqual(rs.indices,js.indices);}});

test('committed WASM is byte-identical to an offline rebuild',async t=>{if(spawnSync('cargo',['--version']).error){t.skip('cargo is unavailable');return;}const directory=await mkdtemp(join(tmpdir(),'briskmap-wasm-'));try{const result=spawnSync('cargo',['build','--offline','--release','--target','wasm32-unknown-unknown','--manifest-path',new URL('../../rust/Cargo.toml',import.meta.url).pathname],{env:{...process.env,CARGO_TARGET_DIR:directory},encoding:'utf8'});assert.equal(result.status,0,result.stderr);const built=await readFile(join(directory,'wasm32-unknown-unknown','release','briskmap_mesher.wasm'));assert.deepEqual(built,await readFile(new URL('../../src/engine/mesher.wasm',import.meta.url)));}finally{await rm(directory,{recursive:true,force:true});}});
